name: StandardRB

on: [push]

jobs:
  standardrb:
    name: StandardRB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec standardrb --format github --parallel
